---
  name: Release Please
  on:
    push:
      branches:
        - main
  
  permissions:
    contents: write
    pull-requests: write
  
  jobs:
    release-please:
      runs-on: ubuntu-latest
      steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: us-west-2
            role-to-assume: arn:aws:iam::337909763509:user/Administrator
            role-duration-seconds: 900
            role-session-name: ${{ github.run_id }}
        - name: Get git credentials
          uses: aws-actions/aws-secretsmanager-get-secrets@v2
          with:
            parse-json-secrets: true
            secret-ids: |
              arn:aws:secretsmanager:us-west-2:337909763509:secret:github/release-please/pat-YJ2cZI
  
        - uses: google-github-actions/release-please-action@v4
          with:
            release-type: node
            token: ${{ secrets.GITHUB_TOKEN }}
  