name: Release and Cleanup

permissions:
  id-token: write
  contents: write

on:
  push:
    branches: main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2 
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 900
          role-session-name: ${{ github.run_id }}

      - name: Get GitHub PAT from AWS Secrets Manager
        run: |
          SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id github/release-please/pat --query SecretString --output text)
          echo "GITHUB_TOKEN=$SECRET_VALUE" >> $GITHUB_ENV

      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ env.GITHUB_TOKEN }}