name: Release and Cleanup

permissions:
  id-token: write
  contents: write

on:
  push:
    branches: main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2 
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 900
          role-session-name: ${{ github.run_id }}

      # - name: Get GitHub PAT from AWS Secrets Manager
      #   run: |
      #     SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id github/release-please/pat --query SecretString --output text)
      #     echo "GITHUB_TOKEN=$SECRET_VALUE" >> $GITHUB_ENV

      # - uses: googleapis/release-please-action@v4
      #   with:
      #     release-type: node
      #     token: ${{ env.GITHUB_TOKEN }}

      - name: Get GitHub PAT from AWS Secrets Manager
        run: |
          echo "Attempting to fetch secret..."
          SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id github/release-please/pat --query SecretString --output text)
          if [ -z "$SECRET_VALUE" ]; then
            echo "Error: Failed to retrieve secret value"
            exit 1
          fi
          echo "Successfully retrieved secret"
          echo "GITHUB_TOKEN=$SECRET_VALUE" >> $GITHUB_ENV

      - name: Basic GitHub API Test
        run: |
          # Test the token with a basic GitHub API call
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/user

      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ env.GITHUB_TOKEN }}